## NumPy Matrix Multiplication

it is important to know that NumPy support several types of matrix multiplication.

### NumPy's `matmul` fuction

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
a.shape

(2, 4)

In [4]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
b.shape

(4, 3)

In [6]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [7]:
c.shape

(2, 3)

If you matrices have imcompatible shapes, you'll get an error, like following:

In [8]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

### NumPy's `dot` function

In [9]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [11]:
a.dot(a) # you can call `dot` directly on the `ndarray`

array([[ 7, 10],
       [15, 22]])

In [12]:
np.matmul(a, a)

array([[ 7, 10],
       [15, 22]])

You can read more about the differences in the [**`matmul`**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) and [**`dot`**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) documentation.